### PR TITLE
[CORE] Error for type casts in version preprocessor macros

### PR DESCRIPTION
**Pull request by lmancini**
The C preprocessor doesn't understand type casts, so checking for the MSXgl version causes the compilation to fail with the error reported below. Removing the type casts from the `VERSION_{}` macros allows to correclty check for MSXgl version:

```
Compiling ./chronorunner.c using SDCC C compiler...
Execute: [...]
./chronorunner.c:6:5: error: missing binary operator before token "1"
Command failed: [...]
Exit code: 1
Error: Error: Compile error! Code: 1
```

```c
#if MSXGL_VERSION < VERSION(1, 3, 7)
#error Please build with MSXgl >=1.3.7
#endif
```

### CODE REVIEW

**Comment by aoineko-fr** [comment]
Fixed in (incoming) MSXgl 1.4
